services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sep490_backend
    ports:
      - "7167:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Development}
      - ASPNETCORE_URLS=${ASPNETCORE_URLS:-http://+:8080}
      - FRONTEND_BASE_URL=${FRONTEND_BASE_URL}
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - JWT_KEY=${JWT_KEY}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - EMAIL_SMTP_SERVER=${EMAIL_SMTP_SERVER}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_SENDER=${EMAIL_SENDER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - REDIS_CONNECTION=${REDIS_CONNECTION}
    networks:
      - dokploy-network
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 1.5G
        reservations:
          cpus: '0.5'
          memory: 512M
    restart: unless-stopped

networks:
  dokploy-network:
    external: true
