// <auto-generated />
using System;
using MTCA.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MTCA.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MTCA.Domain.Analytics.GeneratedVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("PracticeSessionId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionVersionId")
                        .HasColumnType("int");

                    b.Property<string>("ResolvedAnswerJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResolvedVarsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Seed")
                        .HasColumnType("bigint");

                    b.Property<int?>("SubmissionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PracticeSessionId")
                        .HasDatabaseName("IX_GeneratedVariant_PracticeSessionId");

                    b.HasIndex("QuestionVersionId")
                        .HasDatabaseName("IX_GeneratedVariant_QuestionVersionId");

                    b.HasIndex("SubmissionId")
                        .HasDatabaseName("IX_GeneratedVariant_SubmissionId");

                    b.ToTable("GeneratedVariant", null, t =>
                        {
                            t.HasCheckConstraint("CK_GeneratedVariant_OneContext", "(CASE WHEN [SubmissionId] IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN [PracticeSessionId] IS NOT NULL THEN 1 ELSE 0 END) = 1");
                        });
                });

            modelBuilder.Entity("MTCA.Domain.Classrooms.Classroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("JoinCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("JoinCodeEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<string>("TeacherUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedById")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("JoinCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_Classroom_JoinCode")
                        .HasFilter("[JoinCode] IS NOT NULL");

                    b.HasIndex("SemesterId");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("IX_Classroom_SubjectId");

                    b.HasIndex("TeacherUserId")
                        .HasDatabaseName("IX_Classroom_TeacherUserId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Classroom", (string)null);
                });

            modelBuilder.Entity("MTCA.Domain.Classrooms.ClassroomStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ClassroomId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("StudentUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("StudentUserId")
                        .HasDatabaseName("IX_ClassroomStudent_StudentUserId");

                    b.HasIndex("ClassroomId", "StudentUserId")
                        .IsUnique()
                        .HasDatabaseName("UQ_ClassroomStudent_Classroom_Student");

                    b.ToTable("ClassroomStudent", (string)null);
                });

            modelBuilder.Entity("MTCA.Domain.ExamBlueprints.BlueprintCell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("BloomLevel")
                        .HasColumnType("tinyint");

                    b.Property<int>("BlueprintVersionId")
                        .HasColumnType("int");

                    b.Property<int>("ChapterId")
                        .HasColumnType("int");

                    b.Property<double?>("DifficultyHint")
                        .HasColumnType("float");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("int");

                    b.Property<decimal>("ScorePerQuestion")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("BlueprintVersionId", "ChapterId", "BloomLevel")
                        .IsUnique()
                        .HasDatabaseName("UQ_BlueprintCell_Version_Chapter_Bloom");

                    b.ToTable("BlueprintCell", (string)null);
                });

            modelBuilder.Entity("MTCA.Domain.ExamBlueprints.ExamBlueprint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CurrentVersionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OwnerId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedById")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CurrentVersionId");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("IX_ExamBlueprint_OwnerId");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("IX_ExamBlueprint_SubjectId");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("SubjectId", "OwnerId", "Name")
                        .HasDatabaseName("IX_ExamBlueprint_Identity");

                    b.ToTable("ExamBlueprint", (string)null);
                });

            modelBuilder.Entity("MTCA.Domain.ExamBlueprints.ExamBlueprintVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("BlueprintId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("DurationMin")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalScore")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(10.00m);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedById")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BlueprintId")
                        .IsUnique()
                        .HasDatabaseName("UQ_ExamBlueprintVersion_Blueprint_Active")
                        .HasFilter("[Status] = 1");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("BlueprintId", "Status")
                        .HasDatabaseName("IX_ExamBlueprintVersion_Blueprint_Status");

                    b.HasIndex("BlueprintId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_ExamBlueprintVersion_Blueprint_Version");

                    b.ToTable("ExamBlueprintVersion", (string)null);
                });

            modelBuilder.Entity("MTCA.Domain.ExamSessions.ExamSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CancelReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CancelledById")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ClassroomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DurationMin")
                        .HasColumnType("int");

                    b.Property<byte>("EarlySubmitPolicy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<int?>("MinDurationMinutes")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("ShuffleSeed")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedById")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CancelledById");

                    b.HasIndex("ClassroomId")
                        .HasDatabaseName("IX_ExamSession_ClassroomId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ExamSession_Status");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("ExamId", "ClassroomId")
                        .IsUnique()
                        .HasDatabaseName("UQ_ExamSession_Exam_Classroom");

                    b.ToTable("ExamSession", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExamSession_MinDurationPolicy", "([EarlySubmitPolicy] = 2 AND [MinDurationMinutes] IS NOT NULL) OR ([EarlySubmitPolicy] <> 2 AND [MinDurationMinutes] IS NULL)");
                        });
                });

            modelBuilder.Entity("MTCA.Domain.ExamSessions.Submission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("ExamSessionId")
                        .HasColumnType("int");

                    b.Property<int>("ExamVariantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastHeartbeatAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<string>("StudentUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TimerPausedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimerStartedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("TotalPausedMs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<decimal?>("TotalScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("ExamVariantId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Submission_Status");

                    b.HasIndex("StudentUserId")
                        .HasDatabaseName("IX_Submission_StudentUserId");

                    b.HasIndex("ExamSessionId", "StudentUserId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Submission_Session_Student");

                    b.ToTable("Submission", (string)null);
                });

            modelBuilder.Entity("MTCA.Domain.ExamSessions.SubmissionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExamVariantQuestionId")
                        .HasColumnType("int");

                    b.Property<decimal>("MaxScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("PrtFeedbackJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RawAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResolvedVarsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExamVariantQuestionId");

                    b.HasIndex("SubmissionId")
                        .HasDatabaseName("IX_SubmissionItem_SubmissionId");

                    b.HasIndex("SubmissionId", "ExamVariantQuestionId")
                        .IsUnique()
                        .HasDatabaseName("UQ_SubmissionItem_Submission_Question");

                    b.ToTable("SubmissionItem", (string)null);
                });

            modelBuilder.Entity("MTCA.Domain.Exams.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlueprintVersionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationMin")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("ResultVisibilityTiming")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<bool>("ShowCorrectAnswers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("ShowTotalScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("ShuffleOptions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("ShuffleQuestions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedById")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("VariantCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("BlueprintVersionId")
                        .HasDatabaseName("IX_Exam_BlueprintVersionId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Exam_Status");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("IX_Exam_SubjectId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Exam", (string)null);
                });

            modelBuilder.Entity("MTCA.Domain.Exams.ExamVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<int>("VariantNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ExamId")
                        .HasDatabaseName("IX_ExamVariant_ExamId");

                    b.HasIndex("ExamId", "VariantNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_ExamVariant_Exam_Number");

                    b.ToTable("ExamVariant", (string)null);
                });

            modelBuilder.Entity("MTCA.Domain.Exams.ExamVariantQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExamVariantId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionVersionId")
                        .HasColumnType("int");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionVersionId")
                        .HasDatabaseName("IX_ExamVariantQuestion_QuestionVersionId");

                    b.HasIndex("ExamVariantId", "QuestionVersionId")
                        .IsUnique()
                        .HasDatabaseName("UQ_ExamVariantQuestion_Variant_Version");

                    b.ToTable("ExamVariantQuestion", (string)null);
                });

            modelBuilder.Entity("MTCA.Domain.Identity.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("MTCA.Domain.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MTCA.Domain.Identity.UserProfile", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nickname")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("NicknameChangedInSemesterId")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.HasIndex("Nickname")
                        .IsUnique()
                        .HasDatabaseName("UQ_UserProfile_Nickname")
                        .HasFilter("[Nickname] IS NOT NULL");

                    b.HasIndex("NicknameChangedInSemesterId");

                    b.HasIndex("StudentCode")
                        .IsUnique();

                    b.ToTable("UserProfile", (string)null);
                });

            modelBuilder.Entity("MTCA.Domain.Logging.EventLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActorId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("ActorId", "Timestamp")
                        .HasDatabaseName("IX_EventLog_Actor_Timestamp");

                    b.HasIndex("Type", "Timestamp")
                        .HasDatabaseName("IX_EventLog_Type_Timestamp");

                    b.ToTable("EventLog", (string)null);
                });

            modelBuilder.Entity("MTCA.Domain.MasterData.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId", "OrderIndex")
                        .IsUnique()
                        .HasDatabaseName("UQ_Chapter_Subject_Order");

                    b.ToTable("Chapter", (string)null);
                });

            modelBuilder.Entity("MTCA.Domain.MasterData.Semester", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Semester", (string)null);
                });

            modelBuilder.Entity("MTCA.Domain.MasterData.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Subject", (string)null);
                });

            modelBuilder.Entity("MTCA.Domain.Practice.PracticeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("PracticeSessionId")
                        .HasColumnType("int");

                    b.Property<string>("PrtFeedbackJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionVersionId")
                        .HasColumnType("int");

                    b.Property<string>("RawAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResolvedVarsJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionVersionId");

                    b.HasIndex("PracticeSessionId", "AnsweredAt")
                        .HasDatabaseName("IX_PracticeItem_Session_Answered");

                    b.ToTable("PracticeItem", (string)null);
                });

            modelBuilder.Entity("MTCA.Domain.Practice.PracticeSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfigJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("StudentUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int?>("TotalQuestions")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("SemesterId");

                    b.HasIndex("StudentUserId", "StartedAt")
                        .HasDatabaseName("IX_PracticeSession_Student_Started");

                    b.HasIndex("SubjectId", "StartedAt")
                        .HasDatabaseName("IX_PracticeSession_Subject_Started");

                    b.ToTable("PracticeSession", (string)null);
                });

            modelBuilder.Entity("MTCA.Domain.QuestionBank.PrtRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("ConditionType")
                        .HasColumnType("tinyint");

                    b.Property<string>("FeedbackText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentRuleId")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("QuestionBlankId")
                        .HasColumnType("int");

                    b.Property<string>("TargetExpression")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentRuleId")
                        .HasDatabaseName("IX_PrtRule_ParentRuleId");

                    b.HasIndex("QuestionBlankId", "Priority")
                        .HasDatabaseName("IX_PrtRule_Blank_Priority");

                    b.ToTable("PrtRule", (string)null);
                });

            modelBuilder.Entity("MTCA.Domain.QuestionBank.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("BloomLevel")
                        .HasColumnType("tinyint");

                    b.Property<int>("ChapterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CurrentVersionId")
                        .HasColumnType("int");

                    b.Property<double>("DifficultyEmpirical")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.5);

                    b.Property<double>("DifficultyExpected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.5);

                    b.Property<int>("QuestionBankId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedById")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId")
                        .HasDatabaseName("IX_Question_ChapterId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CurrentVersionId");

                    b.HasIndex("QuestionBankId")
                        .HasDatabaseName("IX_Question_QuestionBankId");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("SubjectId", "BloomLevel")
                        .HasDatabaseName("IX_Question_Subject_Bloom");

                    b.ToTable("Question", null, t =>
                        {
                            t.HasCheckConstraint("CK_Question_DifficultyEmpirical_Range", "[DifficultyEmpirical] BETWEEN 0 AND 1");

                            t.HasCheckConstraint("CK_Question_DifficultyExpected_Range", "[DifficultyExpected] BETWEEN 0 AND 1");
                        });
                });

            modelBuilder.Entity("MTCA.Domain.QuestionBank.QuestionBank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OwnerId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte>("Purpose")
                        .HasColumnType("tinyint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedById")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("IX_QuestionBank_OwnerId");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("SubjectId", "Purpose")
                        .IsUnique()
                        .HasDatabaseName("UQ_QuestionBank_Subject_Purpose_SubjectBank")
                        .HasFilter("[OwnerId] IS NULL");

                    b.ToTable("QuestionBank", (string)null);
                });

            modelBuilder.Entity("MTCA.Domain.QuestionBank.QuestionBlank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlankIndex")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("QuestionVersionId")
                        .HasColumnType("int");

                    b.Property<string>("TargetExpression")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetMathJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionVersionId", "BlankIndex")
                        .IsUnique()
                        .HasDatabaseName("UQ_QuestionBlank_Version_Index");

                    b.ToTable("QuestionBlank", (string)null);
                });

            modelBuilder.Entity("MTCA.Domain.QuestionBank.QuestionOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentLatex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentMathJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("QuestionVersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionVersionId", "OrderIndex")
                        .IsUnique()
                        .HasDatabaseName("UQ_QuestionOption_Version_Order");

                    b.ToTable("QuestionOption", (string)null);
                });

            modelBuilder.Entity("MTCA.Domain.QuestionBank.QuestionProposal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReviewerId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedById")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("QuestionId");

                    b.HasIndex("ReviewerId")
                        .HasDatabaseName("IX_QuestionProposal_ReviewerId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_QuestionProposal_Status");

                    b.HasIndex("UpdatedById");

                    b.ToTable("QuestionProposal", (string)null);
                });

            modelBuilder.Entity("MTCA.Domain.QuestionBank.QuestionVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyLatex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BodyMathJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("TemplateVarsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("QuestionId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_QuestionVersion_Question_Version");

                    b.ToTable("QuestionVersion", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MTCA.Domain.Analytics.GeneratedVariant", b =>
                {
                    b.HasOne("MTCA.Domain.Practice.PracticeSession", "PracticeSession")
                        .WithMany()
                        .HasForeignKey("PracticeSessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MTCA.Domain.QuestionBank.QuestionVersion", "QuestionVersion")
                        .WithMany()
                        .HasForeignKey("QuestionVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTCA.Domain.ExamSessions.Submission", "Submission")
                        .WithMany()
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PracticeSession");

                    b.Navigation("QuestionVersion");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("MTCA.Domain.Classrooms.Classroom", b =>
                {
                    b.HasOne("MTCA.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTCA.Domain.MasterData.Semester", "Semester")
                        .WithMany()
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTCA.Domain.MasterData.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTCA.Domain.Identity.ApplicationUser", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTCA.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Semester");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("MTCA.Domain.Classrooms.ClassroomStudent", b =>
                {
                    b.HasOne("MTCA.Domain.Classrooms.Classroom", "Classroom")
                        .WithMany("Students")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTCA.Domain.Identity.ApplicationUser", "Student")
                        .WithMany()
                        .HasForeignKey("StudentUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MTCA.Domain.ExamBlueprints.BlueprintCell", b =>
                {
                    b.HasOne("MTCA.Domain.ExamBlueprints.ExamBlueprintVersion", "BlueprintVersion")
                        .WithMany("Cells")
                        .HasForeignKey("BlueprintVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MTCA.Domain.MasterData.Chapter", "Chapter")
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BlueprintVersion");

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("MTCA.Domain.ExamBlueprints.ExamBlueprint", b =>
                {
                    b.HasOne("MTCA.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTCA.Domain.ExamBlueprints.ExamBlueprintVersion", "CurrentVersion")
                        .WithMany()
                        .HasForeignKey("CurrentVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MTCA.Domain.Identity.ApplicationUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MTCA.Domain.MasterData.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTCA.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CurrentVersion");

                    b.Navigation("Owner");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("MTCA.Domain.ExamBlueprints.ExamBlueprintVersion", b =>
                {
                    b.HasOne("MTCA.Domain.ExamBlueprints.ExamBlueprint", "Blueprint")
                        .WithMany("Versions")
                        .HasForeignKey("BlueprintId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTCA.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTCA.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Blueprint");
                });

            modelBuilder.Entity("MTCA.Domain.ExamSessions.ExamSession", b =>
                {
                    b.HasOne("MTCA.Domain.Identity.ApplicationUser", "CancelledBy")
                        .WithMany()
                        .HasForeignKey("CancelledById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MTCA.Domain.Classrooms.Classroom", "Classroom")
                        .WithMany()
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTCA.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTCA.Domain.Exams.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTCA.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CancelledBy");

                    b.Navigation("Classroom");

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("MTCA.Domain.ExamSessions.Submission", b =>
                {
                    b.HasOne("MTCA.Domain.ExamSessions.ExamSession", "ExamSession")
                        .WithMany("Submissions")
                        .HasForeignKey("ExamSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTCA.Domain.Exams.ExamVariant", "ExamVariant")
                        .WithMany()
                        .HasForeignKey("ExamVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTCA.Domain.Identity.ApplicationUser", "Student")
                        .WithMany()
                        .HasForeignKey("StudentUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExamSession");

                    b.Navigation("ExamVariant");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MTCA.Domain.ExamSessions.SubmissionItem", b =>
                {
                    b.HasOne("MTCA.Domain.Exams.ExamVariantQuestion", "ExamVariantQuestion")
                        .WithMany()
                        .HasForeignKey("ExamVariantQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTCA.Domain.ExamSessions.Submission", "Submission")
                        .WithMany("Items")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExamVariantQuestion");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("MTCA.Domain.Exams.Exam", b =>
                {
                    b.HasOne("MTCA.Domain.ExamBlueprints.ExamBlueprintVersion", "BlueprintVersion")
                        .WithMany()
                        .HasForeignKey("BlueprintVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTCA.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTCA.Domain.MasterData.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTCA.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BlueprintVersion");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("MTCA.Domain.Exams.ExamVariant", b =>
                {
                    b.HasOne("MTCA.Domain.Identity.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTCA.Domain.Exams.Exam", "Exam")
                        .WithMany("Variants")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("MTCA.Domain.Exams.ExamVariantQuestion", b =>
                {
                    b.HasOne("MTCA.Domain.Exams.ExamVariant", "ExamVariant")
                        .WithMany("Questions")
                        .HasForeignKey("ExamVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTCA.Domain.QuestionBank.QuestionVersion", "QuestionVersion")
                        .WithMany()
                        .HasForeignKey("QuestionVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExamVariant");

                    b.Navigation("QuestionVersion");
                });

            modelBuilder.Entity("MTCA.Domain.Identity.UserProfile", b =>
                {
                    b.HasOne("MTCA.Domain.MasterData.Semester", "NicknameChangedInSemester")
                        .WithMany()
                        .HasForeignKey("NicknameChangedInSemesterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MTCA.Domain.Identity.ApplicationUser", "User")
                        .WithOne("Profile")
                        .HasForeignKey("MTCA.Domain.Identity.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NicknameChangedInSemester");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MTCA.Domain.Logging.EventLog", b =>
                {
                    b.HasOne("MTCA.Domain.Identity.ApplicationUser", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("MTCA.Domain.MasterData.Chapter", b =>
                {
                    b.HasOne("MTCA.Domain.MasterData.Subject", "Subject")
                        .WithMany("Chapters")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("MTCA.Domain.Practice.PracticeItem", b =>
                {
                    b.HasOne("MTCA.Domain.Practice.PracticeSession", "PracticeSession")
                        .WithMany("Items")
                        .HasForeignKey("PracticeSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTCA.Domain.QuestionBank.QuestionVersion", "QuestionVersion")
                        .WithMany()
                        .HasForeignKey("QuestionVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PracticeSession");

                    b.Navigation("QuestionVersion");
                });

            modelBuilder.Entity("MTCA.Domain.Practice.PracticeSession", b =>
                {
                    b.HasOne("MTCA.Domain.MasterData.Semester", "Semester")
                        .WithMany()
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTCA.Domain.Identity.ApplicationUser", "Student")
                        .WithMany()
                        .HasForeignKey("StudentUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTCA.Domain.MasterData.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Semester");

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("MTCA.Domain.QuestionBank.PrtRule", b =>
                {
                    b.HasOne("MTCA.Domain.QuestionBank.PrtRule", "ParentRule")
                        .WithMany("ChildRules")
                        .HasForeignKey("ParentRuleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MTCA.Domain.QuestionBank.QuestionBlank", "QuestionBlank")
                        .WithMany("PrtRules")
                        .HasForeignKey("QuestionBlankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentRule");

                    b.Navigation("QuestionBlank");
                });

            modelBuilder.Entity("MTCA.Domain.QuestionBank.Question", b =>
                {
                    b.HasOne("MTCA.Domain.MasterData.Chapter", "Chapter")
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTCA.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTCA.Domain.QuestionBank.QuestionVersion", "CurrentVersion")
                        .WithMany()
                        .HasForeignKey("CurrentVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MTCA.Domain.QuestionBank.QuestionBank", "Bank")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionBankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTCA.Domain.MasterData.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTCA.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Bank");

                    b.Navigation("Chapter");

                    b.Navigation("CurrentVersion");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("MTCA.Domain.QuestionBank.QuestionBank", b =>
                {
                    b.HasOne("MTCA.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTCA.Domain.Identity.ApplicationUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MTCA.Domain.MasterData.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTCA.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Owner");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("MTCA.Domain.QuestionBank.QuestionBlank", b =>
                {
                    b.HasOne("MTCA.Domain.QuestionBank.QuestionVersion", "QuestionVersion")
                        .WithMany("Blanks")
                        .HasForeignKey("QuestionVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionVersion");
                });

            modelBuilder.Entity("MTCA.Domain.QuestionBank.QuestionOption", b =>
                {
                    b.HasOne("MTCA.Domain.QuestionBank.QuestionVersion", "QuestionVersion")
                        .WithMany("Options")
                        .HasForeignKey("QuestionVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionVersion");
                });

            modelBuilder.Entity("MTCA.Domain.QuestionBank.QuestionProposal", b =>
                {
                    b.HasOne("MTCA.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTCA.Domain.QuestionBank.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTCA.Domain.Identity.ApplicationUser", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MTCA.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Question");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("MTCA.Domain.QuestionBank.QuestionVersion", b =>
                {
                    b.HasOne("MTCA.Domain.Identity.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTCA.Domain.QuestionBank.Question", "Question")
                        .WithMany("Versions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("MTCA.Domain.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MTCA.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MTCA.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("MTCA.Domain.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MTCA.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MTCA.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MTCA.Domain.Classrooms.Classroom", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("MTCA.Domain.ExamBlueprints.ExamBlueprint", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("MTCA.Domain.ExamBlueprints.ExamBlueprintVersion", b =>
                {
                    b.Navigation("Cells");
                });

            modelBuilder.Entity("MTCA.Domain.ExamSessions.ExamSession", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("MTCA.Domain.ExamSessions.Submission", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MTCA.Domain.Exams.Exam", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("MTCA.Domain.Exams.ExamVariant", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("MTCA.Domain.Identity.ApplicationUser", b =>
                {
                    b.Navigation("Profile");
                });

            modelBuilder.Entity("MTCA.Domain.MasterData.Subject", b =>
                {
                    b.Navigation("Chapters");
                });

            modelBuilder.Entity("MTCA.Domain.Practice.PracticeSession", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MTCA.Domain.QuestionBank.PrtRule", b =>
                {
                    b.Navigation("ChildRules");
                });

            modelBuilder.Entity("MTCA.Domain.QuestionBank.Question", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("MTCA.Domain.QuestionBank.QuestionBank", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("MTCA.Domain.QuestionBank.QuestionBlank", b =>
                {
                    b.Navigation("PrtRules");
                });

            modelBuilder.Entity("MTCA.Domain.QuestionBank.QuestionVersion", b =>
                {
                    b.Navigation("Blanks");

                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
