// <auto-generated />
using System;
using Backend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(MtcaSep490G26Context))]
    [Migration("20260503230759_AddGradingStateColumns")]
    partial class AddGradingStateColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.BlankInput", b =>
                {
                    b.Property<int>("QuestionAnswerId")
                        .HasColumnType("int");

                    b.Property<int>("InputTypeId")
                        .HasColumnType("int");

                    b.Property<byte[]>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("QuestionAnswerId", "InputTypeId")
                        .HasName("PK__BlankInp__3A18E47A824B6BDA");

                    b.HasIndex("InputTypeId");

                    b.ToTable("BlankInputs");
                });

            modelBuilder.Entity("Backend.Models.Chapter", b =>
                {
                    b.Property<int>("ChapterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChapterId"));

                    b.Property<byte[]>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("ChapterId")
                        .HasName("PK__Chapters__0893A36AEE81EE8B");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("Backend.Models.Class", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassId"));

                    b.Property<byte[]>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("InvitationCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.Property<int>("InvitationCodeStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("ClassId")
                        .HasName("PK__Classes__CB1927C04A621E7C");

                    b.HasIndex("SemesterId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.HasIndex(new[] { "InvitationCode" }, "UQ__Classes__286690FF0D037D77")
                        .IsUnique();

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("Backend.Models.ClassMember", b =>
                {
                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<byte[]>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("MemberStatus")
                        .HasColumnType("int");

                    b.HasKey("ClassId", "StudentId")
                        .HasName("PK__ClassMem__4835757955CD1CFB");

                    b.HasIndex("StudentId");

                    b.ToTable("ClassMembers");
                });

            modelBuilder.Entity("Backend.Models.Exam", b =>
                {
                    b.Property<int>("ExamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamId"));

                    b.Property<int>("AnswerTimingMode")
                        .HasColumnType("int");

                    b.Property<int?>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CloseAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int?>("ExamBlueprintId")
                        .HasColumnType("int");

                    b.Property<int>("MaxAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("OpenAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ShowAnswer")
                        .HasColumnType("int");

                    b.Property<int>("ShowScore")
                        .HasColumnType("int");

                    b.Property<bool>("ShuffleQuestion")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<DateTime?>("VisibleFrom")
                        .HasColumnType("datetime2");

                    b.HasKey("ExamId")
                        .HasName("PK__Exams__297521C70CDECF29");

                    b.HasIndex("ClassId");

                    b.HasIndex("ExamBlueprintId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("Backend.Models.ExamBlueprint", b =>
                {
                    b.Property<int>("ExamBlueprintId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamBlueprintId"));

                    b.Property<byte[]>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("ExamBlueprintId")
                        .HasName("PK__ExamBlue__C1EF9CEF974A7B17");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("ExamBlueprints");
                });

            modelBuilder.Entity("Backend.Models.ExamBlueprintChapter", b =>
                {
                    b.Property<int>("ExamBlueprintId")
                        .HasColumnType("int");

                    b.Property<int>("ChapterId")
                        .HasColumnType("int");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<byte[]>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("TotalOfQuestions")
                        .HasColumnType("int");

                    b.HasKey("ExamBlueprintId", "ChapterId", "Difficulty")
                        .HasName("PK__ExamBlue__E9BFA7D0F0EC64DB");

                    b.HasIndex("ChapterId");

                    b.ToTable("ExamBlueprintChapter", (string)null);
                });

            modelBuilder.Entity("Backend.Models.GroupAnswer", b =>
                {
                    b.Property<int>("GroupAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupAnswerId"));

                    b.Property<int?>("DependsOnGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("GroupAnswerId")
                        .HasName("PK__GroupAns__2DBBC7BF07E0BCF8");

                    b.HasIndex("DependsOnGroupId");

                    b.ToTable("GroupAnswers");
                });

            modelBuilder.Entity("Backend.Models.InputType", b =>
                {
                    b.Property<int>("InputTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InputTypeId"));

                    b.Property<string>("GroupType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Regex")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("InputTypeId")
                        .HasName("PK__InputTyp__CA63BB5A702ACA0D");

                    b.ToTable("InputTypes");
                });

            modelBuilder.Entity("Backend.Models.Paper", b =>
                {
                    b.Property<int>("PaperId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaperId"));

                    b.Property<int?>("Code")
                        .HasColumnType("int");

                    b.Property<int?>("ExamId")
                        .HasColumnType("int");

                    b.HasKey("PaperId")
                        .HasName("PK__Papers__AB86120B71F05C29");

                    b.HasIndex("ExamId");

                    b.ToTable("Papers");
                });

            modelBuilder.Entity("Backend.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<int>("ChapterId")
                        .HasColumnType("int");

                    b.Property<byte[]>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("QuestionContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("QuestionPurpose")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.HasKey("QuestionId")
                        .HasName("PK__Question__0DC06FACF1A0E339");

                    b.HasIndex("ChapterId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Backend.Models.QuestionAnswer", b =>
                {
                    b.Property<int>("QuestionAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionAnswerId"));

                    b.Property<byte[]>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GroupAnswerId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int?>("Point")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("QuestionAnswerId")
                        .HasName("PK__Question__86BEDFCF73CA15C6");

                    b.HasIndex("GroupAnswerId");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionAnswers");
                });

            modelBuilder.Entity("Backend.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE1A13F124CB");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Backend.Models.Semester", b =>
                {
                    b.Property<int>("SemesterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SemesterId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("SemesterId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("Semesters");
                });

            modelBuilder.Entity("Backend.Models.StudentAnswer", b =>
                {
                    b.Property<int>("StudentAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentAnswerId"));

                    b.Property<byte[]>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<decimal?>("PointsEarned")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("QuestionAnswerId")
                        .HasColumnType("int");

                    b.Property<string>("Response")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("int");

                    b.HasKey("StudentAnswerId")
                        .HasName("PK__StudentA__6E3EA405089AC96F");

                    b.HasIndex("QuestionAnswerId");

                    b.HasIndex("SubmissionId", "IsCorrect")
                        .HasDatabaseName("IX_StudentAnswers_Submission_IsCorrect");

                    b.ToTable("StudentAnswers");
                });

            modelBuilder.Entity("Backend.Models.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectId"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<byte[]>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("SubjectId")
                        .HasName("PK__Subjects__AC1BA3A86E08C448");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("Backend.Models.Submission", b =>
                {
                    b.Property<int>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubmissionId"));

                    b.Property<byte[]>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("GradingError")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte>("GradingStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<int>("PaperId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalPoints")
                        .HasColumnType("decimal(5, 3)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("SubmissionId")
                        .HasName("PK__Submissi__449EE12553B1053B");

                    b.HasIndex("PaperId");

                    b.HasIndex("StudentId");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<byte[]>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("MustChangePassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("char(60)")
                        .IsFixedLength();

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SecurityStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("StudentId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4C1B357F2D");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534BF4ED69B")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PaperQuestion", b =>
                {
                    b.Property<int>("PaperId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("PaperId", "QuestionId")
                        .HasName("PK__PaperQue__7B5A14F1873A63DF");

                    b.HasIndex("QuestionId");

                    b.ToTable("PaperQuestion", (string)null);
                });

            modelBuilder.Entity("Backend.Models.BlankInput", b =>
                {
                    b.HasOne("Backend.Models.InputType", "InputType")
                        .WithMany("BlankInputs")
                        .HasForeignKey("InputTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_BlankInputs_InputTypes");

                    b.HasOne("Backend.Models.QuestionAnswer", "QuestionAnswer")
                        .WithMany("BlankInputs")
                        .HasForeignKey("QuestionAnswerId")
                        .IsRequired()
                        .HasConstraintName("FK_BlankInputs_QuestionAnswers");

                    b.Navigation("InputType");

                    b.Navigation("QuestionAnswer");
                });

            modelBuilder.Entity("Backend.Models.Chapter", b =>
                {
                    b.HasOne("Backend.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Subject", "Subject")
                        .WithMany("Chapters")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK_Chapters_Subjects");

                    b.HasOne("Backend.Models.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Subject");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("Backend.Models.Class", b =>
                {
                    b.HasOne("Backend.Models.Semester", "Semester")
                        .WithMany("Classes")
                        .HasForeignKey("SemesterId")
                        .IsRequired()
                        .HasConstraintName("FK_Classes_Semesters");

                    b.HasOne("Backend.Models.Subject", "Subject")
                        .WithMany("Classes")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK_Classes_Subjects");

                    b.HasOne("Backend.Models.User", "Teacher")
                        .WithMany("Classes")
                        .HasForeignKey("TeacherId")
                        .IsRequired()
                        .HasConstraintName("FK_Classes_Users");

                    b.Navigation("Semester");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Backend.Models.ClassMember", b =>
                {
                    b.HasOne("Backend.Models.Class", "Class")
                        .WithMany("ClassMembers")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK_ClassMembers_Classes");

                    b.HasOne("Backend.Models.User", "Student")
                        .WithMany("ClassMembers")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_ClassMembers_Users");

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Backend.Models.Exam", b =>
                {
                    b.HasOne("Backend.Models.Class", "Class")
                        .WithMany("Exams")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK_Exams_Classes");

                    b.HasOne("Backend.Models.ExamBlueprint", "ExamBlueprint")
                        .WithMany("Exams")
                        .HasForeignKey("ExamBlueprintId")
                        .HasConstraintName("FK_Exams_ExamBlueprints");

                    b.HasOne("Backend.Models.Subject", "Subject")
                        .WithMany("Exams")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK_Exams_Subjects");

                    b.HasOne("Backend.Models.User", "Teacher")
                        .WithMany("Exams")
                        .HasForeignKey("TeacherId")
                        .IsRequired()
                        .HasConstraintName("FK_Exams_Users");

                    b.Navigation("Class");

                    b.Navigation("ExamBlueprint");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Backend.Models.ExamBlueprint", b =>
                {
                    b.HasOne("Backend.Models.Subject", "Subject")
                        .WithMany("ExamBlueprints")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK_Blueprints_Subjects");

                    b.HasOne("Backend.Models.User", "Teacher")
                        .WithMany("ExamBlueprints")
                        .HasForeignKey("TeacherId")
                        .IsRequired()
                        .HasConstraintName("FK_ExamBlueprints_Users");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Backend.Models.ExamBlueprintChapter", b =>
                {
                    b.HasOne("Backend.Models.Chapter", "Chapter")
                        .WithMany("ExamBlueprintChapters")
                        .HasForeignKey("ChapterId")
                        .IsRequired()
                        .HasConstraintName("FK_EBC_Chapters");

                    b.HasOne("Backend.Models.ExamBlueprint", "ExamBlueprint")
                        .WithMany("ExamBlueprintChapters")
                        .HasForeignKey("ExamBlueprintId")
                        .IsRequired()
                        .HasConstraintName("FK_EBC_Blueprints");

                    b.Navigation("Chapter");

                    b.Navigation("ExamBlueprint");
                });

            modelBuilder.Entity("Backend.Models.GroupAnswer", b =>
                {
                    b.HasOne("Backend.Models.GroupAnswer", "DependsOnGroup")
                        .WithMany("InverseDependsOnGroup")
                        .HasForeignKey("DependsOnGroupId")
                        .HasConstraintName("FK_GroupAnswers_DependsOnGroup");

                    b.Navigation("DependsOnGroup");
                });

            modelBuilder.Entity("Backend.Models.Paper", b =>
                {
                    b.HasOne("Backend.Models.Exam", "Exam")
                        .WithMany("Papers")
                        .HasForeignKey("ExamId")
                        .HasConstraintName("FK_Papers_Exams");

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("Backend.Models.Question", b =>
                {
                    b.HasOne("Backend.Models.Chapter", "Chapter")
                        .WithMany("Questions")
                        .HasForeignKey("ChapterId")
                        .IsRequired()
                        .HasConstraintName("FK_Questions_Chapters");

                    b.HasOne("Backend.Models.User", "CreatedByUser")
                        .WithMany("Questions")
                        .HasForeignKey("CreatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Questions_Users");

                    b.Navigation("Chapter");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Backend.Models.QuestionAnswer", b =>
                {
                    b.HasOne("Backend.Models.GroupAnswer", "GroupAnswer")
                        .WithMany("QuestionAnswers")
                        .HasForeignKey("GroupAnswerId")
                        .HasConstraintName("FK_QuestionAnswers_GroupAnswers");

                    b.HasOne("Backend.Models.Question", "Question")
                        .WithMany("QuestionAnswers")
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("FK_QuestionAnswers_Questions");

                    b.Navigation("GroupAnswer");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Backend.Models.Semester", b =>
                {
                    b.HasOne("Backend.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("Backend.Models.StudentAnswer", b =>
                {
                    b.HasOne("Backend.Models.QuestionAnswer", "QuestionAnswer")
                        .WithMany("StudentAnswers")
                        .HasForeignKey("QuestionAnswerId")
                        .IsRequired()
                        .HasConstraintName("FK_StudentAnswers_QuestionAnswers");

                    b.HasOne("Backend.Models.Submission", "Submission")
                        .WithMany("StudentAnswers")
                        .HasForeignKey("SubmissionId")
                        .IsRequired()
                        .HasConstraintName("FK_StudentAnswers_Submissions");

                    b.Navigation("QuestionAnswer");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("Backend.Models.Subject", b =>
                {
                    b.HasOne("Backend.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("Backend.Models.Submission", b =>
                {
                    b.HasOne("Backend.Models.Paper", "Paper")
                        .WithMany("Submissions")
                        .HasForeignKey("PaperId")
                        .IsRequired()
                        .HasConstraintName("FK_Submissions_Papers");

                    b.HasOne("Backend.Models.User", "Student")
                        .WithMany("Submissions")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_Submissions_Users");

                    b.Navigation("Paper");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.HasOne("Backend.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_Users_Roles");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PaperQuestion", b =>
                {
                    b.HasOne("Backend.Models.Paper", null)
                        .WithMany()
                        .HasForeignKey("PaperId")
                        .IsRequired()
                        .HasConstraintName("FK_PQ_Papers");

                    b.HasOne("Backend.Models.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("FK_PQ_Questions");
                });

            modelBuilder.Entity("Backend.Models.Chapter", b =>
                {
                    b.Navigation("ExamBlueprintChapters");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Backend.Models.Class", b =>
                {
                    b.Navigation("ClassMembers");

                    b.Navigation("Exams");
                });

            modelBuilder.Entity("Backend.Models.Exam", b =>
                {
                    b.Navigation("Papers");
                });

            modelBuilder.Entity("Backend.Models.ExamBlueprint", b =>
                {
                    b.Navigation("ExamBlueprintChapters");

                    b.Navigation("Exams");
                });

            modelBuilder.Entity("Backend.Models.GroupAnswer", b =>
                {
                    b.Navigation("InverseDependsOnGroup");

                    b.Navigation("QuestionAnswers");
                });

            modelBuilder.Entity("Backend.Models.InputType", b =>
                {
                    b.Navigation("BlankInputs");
                });

            modelBuilder.Entity("Backend.Models.Paper", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("Backend.Models.Question", b =>
                {
                    b.Navigation("QuestionAnswers");
                });

            modelBuilder.Entity("Backend.Models.QuestionAnswer", b =>
                {
                    b.Navigation("BlankInputs");

                    b.Navigation("StudentAnswers");
                });

            modelBuilder.Entity("Backend.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Backend.Models.Semester", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("Backend.Models.Subject", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("Classes");

                    b.Navigation("ExamBlueprints");

                    b.Navigation("Exams");
                });

            modelBuilder.Entity("Backend.Models.Submission", b =>
                {
                    b.Navigation("StudentAnswers");
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Navigation("ClassMembers");

                    b.Navigation("Classes");

                    b.Navigation("ExamBlueprints");

                    b.Navigation("Exams");

                    b.Navigation("Questions");

                    b.Navigation("Submissions");
                });
#pragma warning restore 612, 618
        }
    }
}
